# Generated by Django 3.2 on 2021-04-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVresume', '0002_auto_20210409_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='link',
            field=models.CharField(max_length=50),
        ),
    ]
