# Generated by Django 3.2 on 2021-04-12 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CVresume', '0004_resume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certifications',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification', to='CVresume.resume'),
        ),
        migrations.AlterField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu', to='CVresume.resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expi', to='CVresume.resume'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='CVresume.resume'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='CVresume.resume'),
        ),
    ]
